### ISSUE TITLE
How to use /* */ for comments

### ISSUE THREAD

**Issue by levinit** [MhMadHamster/vscode-postcss-language#20]
When I press vscode‘s shortcut <kbd>ctrl</kbd> - <kbd>/</kbd>, the comments style is double slash comments style `//`, How can I use `/* comments */` rather than `//comments` ? Thanks😊

**Comment by levinit** [comment]
Sorry, I am so careless, <kbd>ctrl</kbd>-<kbd>shift</kbd>-<kbd>a</kbd> is block-comment shortcut, it will use `/* */` style.

**Comment by MhMadHamster** [comment]
this issue was fixed in #17 i just forgot to publish it, will do asap

**Comment by levinit** [comment]
good 😃



在 Max Burmagin <notifications@github.com>，2018年1月15日 17:49写道：

this issue was fixed in #17<https://github.com/MhMadHamster/vscode-postcss-language/pull/17> i just forgot to publish it, will do asap

**Comment by danawoodman** [comment]
This is an issue still afaik. If I run comment link I get `//` instead of `/**/`

**Comment by MhMadHamster** [comment]
@danawoodman thanks for the report, what version of extension you are using? i've just tested 2.1.0 in *.pcss file and it works as expected ( `/* */` used for comments )

**Comment by danawoodman** [comment]
I believe the latest? I’ll double check versions and report back

My file is `.css` but the file type is `PostCSS`.

**Comment by danawoodman** [comment]
Think I'm on latest. Have this in my config too:

```json
  "files.associations": {
    "*.css": "postcss"
  },
```

**Comment by MhMadHamster** [comment]
dunno how I can help, I can't reproduce it, even after re-installing the extension 😕

**Comment by danawoodman** [comment]
Did you try with a `.css` file?

**Comment by danawoodman** [comment]
Here is in a `.pcss` file...

![](https://cl.ly/sTHD/Screen%20Recording%202018-06-21%20at%2010.09%20PM.gif)

**Comment by MhMadHamster** [comment]
can you show your `code --list-extensions` ?

**Comment by danawoodman** [comment]
```DavidAnson.vscode-markdownlint
EditorConfig.EditorConfig
Orta.vscode-jest
SirTori.indenticator
Zignd.html-css-class-completion
alefragnani.project-manager
andischerer.theme-atom-one-dark
anseki.vscode-color
bbrakenhoff.solarized-light-custom
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
cpylua.language-postcss
dakara.dakara-foldplus
dbaeumer.jshint
dbaeumer.vscode-eslint
ecmel.vscode-html-css
eg2.tslint
eg2.vscode-npm-script
esbenp.prettier-vscode
fknop.vscode-npm
flowtype.flow-for-vscode
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
idleberg.hopscotch
mechatroner.rainbow-csv
mikestead.dotenv
mkaufman.HTMLHint
mrmlnc.vscode-apache
ms-vscode.node-debug2
ms-vsliveshare.vsliveshare
msjsdiag.debugger-for-chrome
pthorsson.vscode-jsp
redhat.java
ricard.postcss
robertohuertasm.vscode-icons
robinbentley.sass-indented
shinnn.stylelint
streetsidesoftware.code-spell-checker
thenikso.github-plus-theme
tinkertrain.theme-panda
vscjava.vscode-java-debug
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
vscodevim.vim
vsmobile.vscode-react-native
waderyan.gitblame
wayou.vscode-todo-highlight
wix.vscode-import-cost
zhuangtongfa.Material-theme```

**Comment by MhMadHamster** [comment]
you're using [this fork](https://marketplace.visualstudio.com/items?itemName=cpylua.language-postcss), not mine one

**Comment by danawoodman** [comment]
@MhMadHamster what is the name of this extension in the VSCode app store?

**Comment by danawoodman** [comment]
Nevermind, I see it is postcss-sugarss-language

Name confused me, sorry for the false report
